// import './style.css' // Disabled to prevent global style pollution in Micro-frontends (Admin/Host conflict)
export { default as AspectRatio } from './components/aspect-ratio/AspectRatio.vue'
export { default as Dialog } from './components/dialog/Dialog.vue'
export { default as DialogContent } from './components/dialog/DialogContent.vue'
export { default as DialogDescription } from './components/dialog/DialogDescription.vue'
export { default as DialogFooter } from './components/dialog/DialogFooter.vue'
export { default as DialogHeader } from './components/dialog/DialogHeader.vue'
export { default as DialogTitle } from './components/dialog/DialogTitle.vue'
export { default as DialogTrigger } from './components/dialog/DialogTrigger.vue'
export { default as Badge } from './components/badge/Badge.vue'
export { default as Button } from './components/button/Button.vue'
export { default as Card } from './components/card/Card.vue'
export { default as CardHeader } from './components/card/CardHeader.vue'
export { default as CardTitle } from './components/card/CardTitle.vue'
export { default as CardDescription } from './components/card/CardDescription.vue'
export { default as CardContent } from './components/card/CardContent.vue'
export { default as CardFooter } from './components/card/CardFooter.vue'
export { default as ScrollArea } from './components/scroll-area/ScrollArea.vue'
export { default as ScrollBar } from './components/scroll-area/ScrollBar.vue'
export { default as Separator } from './components/separator/Separator.vue'
export { default as Sheet } from './components/sheet/Sheet.vue'
export { default as SheetTrigger } from './components/sheet/SheetTrigger.vue'
export { default as SheetContent } from './components/sheet/SheetContent.vue'
export { default as SheetHeader } from './components/sheet/SheetHeader.vue'
export { default as SheetTitle } from './components/sheet/SheetTitle.vue'
export { default as SheetDescription } from './components/sheet/SheetDescription.vue'
export { default as SheetFooter } from './components/sheet/SheetFooter.vue'
export { default as SheetClose } from './components/sheet/SheetClose.vue'
export { default as Toast } from './components/Toast.vue'

export { default as Toaster } from './components/sonner/Toaster.vue'
export { toast } from 'vue-sonner'

// Export utils
import { cn } from './lib/utils'
export { cn }
